SOCKET_TIMEOUT = 5.0
PORT = 6881
OUTPUT_DIR = "."
OUTPUT_DIR_EXIST_OK = True
PEER_ID_PREFIX = b"-TO0001-"
MAX_SETUP_THREADS = 100
MAX_HANDSHAKE_THREADS = 10
MAX_REQUEST_THREADS = 10
MAX_LISTEN_THREADS = 10
MAX_UPLOAD_THREADS = 10
PROTOCOL = b"BitTorrent protocol"
REQUEST_SLEEP_TIME = 1
BLOCK_SIZE = 2**14

# How long to wait before declaring a thread dead
DEAD_THREAD_TIME = 120

# Num
MAX_PEERS = 10
MAX_PENDING_BLOCK_REQUESTS = 10
BLOCK_REQUEST_TIMEOUT = 10.0

# Sleep Times
TIME_BETWEEN_SENDS = 0
TIME_BETWEEN_PIECE_REQUESTS = 0
KEEP_ALIVE_INTERVAL = 60
# TIME_BETWEEN_PIECE_REQUESTS -= TIME_BETWEEN_SENDS
TIME_BETWEEN_LISTENS = 0
TIME_BETWEEN_PROGRESS_UPDATES = 0.1
